### ISSUE TITLE
Is it possible to retrieve register values as binary data instead of as a list of integers?

### ISSUE THREAD

**Issue by nmuise-barclay** [tiagocoutinho/async_modbus#12]
* Async ModBus version: 0.2.1
* Python version: 3.10
* Operating System: Windows 10

### Description
I'm writing an application that will need to continuously poll a large number of devices for registers and unpack them to the actual underlying data types they represent. However, async_modbus' `read_holding_registers()` method retrieves registers as a series of integers, so in order to decode the retrieved registers to their proper datatype (usually float32), I need to first pack all the registers I retrieved back to binary data before I can actually unpack them to the types I need. Moreover, since the uModbus library's `read_holding_registers()` method retrieves the registers in a binary format, this must mean that async_modbus is unpacking the registers to int16. Therefore, in order for me to retrieve two registers and unpack them to a float32 using async_modbus, umodbus first retrieves the binary register values, async_modbus decodes them to int16, I re-encode them back to binary, and finally I decode them a second time, to float32. Encoding and decoding all the registers twice like this is convoluted and makes me think I'm doing something wrong or using the async_modbus library incorrectly. So is there a way to avoid/disable async_modbus' automatic decoding of all registers to int16?

### What I Did
The following simplified example illustrates my basic workflow for retrieving and decoding registers - I read them using `read_holding_registers()`, pack the returned integers to binary data using `struct`, and unpack the binary data to the type I need using `struct` again:
```python
import asyncio
import async_modbus
import struct

async def main():
    reader, writer = await asyncio.open_connection(host="xxx.yyy.zzz.www", port=502)
    client = async_modbus.AsyncTCPClient(stream=(reader, writer))

    uint16x2 = struct.Struct("HH")
    float32 = struct.Struct("f")

    raw_data = await client.read_holding_registers( slave_id=1, 
                                                    starting_address=29270,
                                                    quantity=8)
    #        = [17680, 16357, 53335, 16356, 39917, 16575, 65373, 17223]

    # re-encoding the data so I can decode it later
    binary_data = [uint16x2.pack(raw_data[i], raw_data[i+1]) for i in range(0, len(raw_data), 2)]
    #           = [b'\x10E\xe5?', b'W\xd0\xe4?', b'\xed\x9b\xbf@', b']\xffGC']

    # decoding the re-encoded data to float32
    decoded_data = [float32.unpack(binary_value)[0] for binary_value in binary_data]
    #            = [1.7911701202392578, 1.787608027458191, 5.987783908843994, 199.9975128173828]

if __name__ == "__main__":
    asyncio.run(main())
```

I tried to find my own solution to avoid the extra encoding/decoding, but I'm not really sure where to look. I thought that the [patches in `umodbus_numpy.py`](https://github.com/tiagocoutinho/async_modbus/blob/master/async_modbus/umodbus_numpy.py#L99) were the reason why async_modbus decodes all registers to int16, but then I realized I don't even have numpy installed, so those patches weren't running anyways. Just to check though, I removed the `from .umodbus_numpy import patch` and the call to `patch()` from the top of `core.py`, and ran the test script I posted above, and it behaved exactly the same, so evidently I don't understand when/where the registers are being decoded to int16.

I would appreciate any guidance here!

**Comment by tiagocoutinho** [comment]
This library tries to patch `umodbus` library with numpy encoders/decoders if numpy is installed. If numpy is not installed, no patching is done and umodbus default encoder/decoder is used.

Looks like you want your own decoder to be used so what I would do is write a patch that works for you. Something like: 

```python
from umodbus import conf, functions

class ReadHoldingRegisters(functions.ReadHoldingRegisters):
    @classmethod
    def create_from_response_pdu(cls, resp_pdu, req_pdu):
        read_holding_registers = cls()
        count = struct.unpack(">H", req_pdu[-2:])[0]
        data = numpy.frombuffer(resp_pdu, dtype=">f2", count=count, offset=2)
        read_holding_registers.data = data
        read_holding_registers.quantity = data.size
        return read_holding_registers


functions.function_code_to_function_map[functions.READ_HOLDING_REGISTERS] = ReadHoldingRegisters
```

This will force `umodbus` to use your class instead of it's own.

**Comment by nmuise-barclay** [comment]
Thanks! Since I wanted to retrieve the data as `bytes` and I'm not using numpy, I just needed to make a slight adjustment to your suggested solution:

```python
from umodbus import functions

def patch_umodbus():
  class ReadHoldingRegisters(functions.ReadHoldingRegisters):
      @classmethod
      def create_from_response_pdu(cls, resp_pdu, req_pdu):
          read_holding_registers = cls()
          count = struct.unpack(">H", req_pdu[-2:])[0]
          data = resp_pdu[4:-2]

          read_holding_registers.data = data
          read_holding_registers.quantity = count
          return read_holding_registers

  functions.function_code_to_function_map[functions.READ_HOLDING_REGISTERS] = ReadHoldingRegisters
```
Then I just call `patch_umodbus()` before entering the application. Thanks again for helping me figure this out!
